In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [3]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
arr4=np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr5=np.ones((2,3))
arr5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr6=np.arange(1,11)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr7=np.arange(1,11,2)
arr7

array([1, 3, 5, 7, 9])

In [11]:
arr8=np.linspace(-10,10,10)
arr8

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
arr9=arr8.copy()
arr9

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
arr9=np.copy(arr8)
arr9

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [14]:
arr10=np.identity(3)
arr10

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
arr2.shape

(3, 3)

In [16]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr3.shape

(2, 2, 2)

In [18]:
arr1.shape

(4,)

In [19]:
arr2.ndim

2

In [20]:
arr3.ndim

3

In [21]:
arr1.ndim

1

In [22]:
arr1.size

4

In [23]:
arr2.size

9

In [24]:
arr3.size

8

In [25]:
arr1.itemsize

4

In [26]:
arr2.itemsize

4

In [27]:
arr3.itemsize

4

In [28]:
arr1.dtype

dtype('int32')

In [29]:
arr2.dtype

dtype('int32')

In [30]:
arr3.dtype

dtype('int32')

In [31]:
arr2.astype('float')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [32]:
arr3.astype('int')

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
arr3.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [34]:
L=range(100)
A=np.arange(100)

In [35]:
L

range(0, 100)

In [36]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
import sys

In [38]:
sys.getsizeof(L[0])

24

In [39]:
sys.getsizeof(L[0])*len(L)

2400

In [40]:
A.itemsize

4

In [41]:
A.itemsize*A.size

400

In [43]:
L1=range(10000000)
L2=range(10000000,20000000)
A1=np.arange(10000000)
A2=np.arange(10000000,20000000)

In [44]:
import time

In [46]:
start=time.time()
L3=[i+j for (i,j) in zip(L1,L2)]
t1=time.time()-start
t1

1.2531507015228271

In [47]:
start=time.time()
c=A1+A2
t2=time.time()-start
t2

0.03203010559082031

In [48]:
t1/t2

39.124151432144345

In [60]:
a=np.arange(1,21).reshape(5,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [59]:
b=np.arange(1,21).reshape(5,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [62]:
b+a


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [63]:
a-b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [64]:
a*b


array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256],
       [289, 324, 361, 400]])

In [65]:
a**b

array([[          1,           4,          27,         256],
       [       3125,       46656,      823543,    16777216],
       [  387420489,  1410065408,  1843829075,  -251658240],
       [-1692154371, -1282129920,  1500973039,           0],
       [ 1681328401,   457441280,  -306639989,           0]], dtype=int32)

In [66]:
a%b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [67]:
a/b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
a==19

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [69]:
a>15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [70]:
b*5

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [ 65,  70,  75,  80],
       [ 85,  90,  95, 100]])

In [72]:
a.dot(np.transpose(b))

array([[  30,   70,  110,  150,  190],
       [  70,  174,  278,  382,  486],
       [ 110,  278,  446,  614,  782],
       [ 150,  382,  614,  846, 1078],
       [ 190,  486,  782, 1078, 1374]])

In [73]:
a+=2

In [74]:
a

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [75]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [77]:
b.min()

1

In [78]:
b.max()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [79]:
b.max()

20

In [80]:
b.max(axis=0)

array([17, 18, 19, 20])

In [81]:
b.min(axis=0)

array([1, 2, 3, 4])

In [82]:
b.max(axis=1)

array([ 4,  8, 12, 16, 20])

In [83]:
b.min(axis=1)

array([ 1,  5,  9, 13, 17])

In [84]:
a.sum(axis=0)

array([55, 60, 65, 70])

In [85]:
a.sum(axis=1)

array([18, 34, 50, 66, 82])

In [86]:
d=np.sin(a)

In [87]:
d

array([[ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725],
       [ 0.14987721,  0.91294525,  0.83665564, -0.00885131]])

In [88]:
np.median(b)

10.5

In [89]:
np.mean(b)

10.5

In [90]:
f=np.arange(10)

In [91]:
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
f[2]

2

In [93]:
f[-2]

8

In [94]:
f[-2+len(f)]

8

In [95]:
f[2:5]

array([2, 3, 4])

In [96]:
f[2:5:2]

array([2, 4])

In [97]:
a

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [98]:
a[0]

array([3, 4, 5, 6])

In [99]:
a[1]

array([ 7,  8,  9, 10])

In [100]:
a[2]

array([11, 12, 13, 14])

In [101]:
a[0][1]

4

In [102]:
a[2:,1:]

array([[12, 13, 14],
       [16, 17, 18],
       [20, 21, 22]])

In [103]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [104]:
arr3[0]

array([[1, 2],
       [3, 4]])

In [105]:
arr3[0][0]

array([1, 2])

In [106]:
arr3[0][0][0]

1

In [107]:
arr3[:,:,1]

array([[2, 4],
       [6, 8]])

In [108]:
arr3[1][:,1]

array([6, 8])

In [109]:
for i in arr2:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [110]:
for i in np.nditer(b):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [111]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
arr[[1]]

NameError: name 'arr' is not defined

In [113]:
arr=np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [114]:
arr[[1,3,4]]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [115]:
arr[[1,3,4],[2,3]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [116]:
arr[[1,3,4]]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [120]:
arr[:,[2,4]]

array([[ 2,  4],
       [ 8, 10],
       [14, 16],
       [20, 22],
       [26, 28]])

In [122]:
d=b>5
b[d]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [123]:
import matplotlib.pyplot as plt

In [138]:
a=np.arange(-5,5,.01)
h3=np.exp(-np.square(a)/2)/(np.sqrt(2*np.pi))
plt.plot(a,h3)

In [1]:
import random

In [ ]:
import random
number_system=random.randint(1,100)
number_user=int(input('Guess a number between 1 and 100 '))
i=1
while(number_user!=number_system):
    
    if(number_user<number_system):
        
        number_user=int(input('Wrong number..please enter a higher number'))
        i=i+1
        
    else:
        
        number_user=int(input('Wrong number..please enter a lower number'))
        i=i+1
        
else:
    print('Winner, number of times= ',i)    
    
    

In [1]:
'KOl'>'Mum'

False

In [2]:
'kol'<'mum'

True